### ISSUE TITLE
How to use placeholder images

### ISSUE THREAD

**Issue by YueJZJM** [lisb/android-gifview#1]
How to use the placeholder image and display it after the gif is successfully downloaded from the Internet

**Comment by YueJZJM** [comment]
@takara727 help me

**Comment by takara727** [comment]
Unfortunately, this library don't support placeholder. We use this library in our products for GifSpan, but this library is in maintenance mode. We will not be adding new features or capabilities. We recommend using Glide, Fresco, or Coil.

**Comment by YueJZJM** [comment]
> Unfortunately, this library don't support placeholder. We use this library in our products for GifSpan, but this library is in maintenance mode. We will not be adding new features or capabilities. We recommend using Glide, Fresco, or Coil.

Thank you for your answer, but this is really unfortunate news for me
